module.exports = {
  path: '/game/bingo/newcard',
  code: `
  $var[B;⒈1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,⒑.1,11.1,12.1,13.1,14.1,15.1]
  $var[I;16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  $var[N;31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  $var[G;46,47,48,49,50,51,52,53,54,55,56,57,58,59,60]
  $var[O;61,62,63,64,65,66,67,68,69,70,71,72,73,74,75]
  
$var[B0;$split[$get[B];,]]
$var[B1;$arrayAt[B0;$randomNumber[1;15]]]
$var[B;$replaceText[$replaceText[$get[B];$get[B1];];,,;,]]
$var[B0;$split[$get[B];,]]
$var[B2;$arrayAt[B0;$randomNumber[1;14]]]
$var[B;$replaceText[$replaceText[$replaceText[$get[B];$get[B1];];$get[B2];];,,;,]]
$var[B0;$split[$get[B];,]]
$var[B3;$arrayAt[B0;$randomNumber[1;13]]]
$var[B;$replaceText[$replaceText[$replaceText[$replaceText[$get[B];$get[B1];];$get[B2];];$get[B3];];,,;,]]
$var[B0;$split[$get[B];,]]
$var[B4;$arrayAt[B0;$randomNumber[1;12]]]
$var[B;$replaceText[$replaceText[$replaceText[$replaceText[$replaceText[$get[B];$get[B1];];$get[B2];];$get[B3];];$get[B4];];,,;,]]
$var[B0;$split[$get[B];,]]
$var[B5;$arrayAt[B0;$randomNumber[1;11]]]
$var[I0;$split[$get[I];,]]
$var[I1;$arrayAt[I0;$randomNumber[1;15]]]
$var[I;$replaceText[$replaceText[$get[I];$get[I1];];,,;,]]
$var[I0;$split[$get[I];,]]
$var[I2;$arrayAt[I0;$randomNumber[1;14]]]
$var[I;$replaceText[$replaceText[$replaceText[$get[I];$get[I1];];$get[I2];];,,;,]]
$var[I0;$split[$get[I];,]]
$var[I3;$arrayAt[I0;$randomNumber[1;13]]]
$var[I;$replaceText[$replaceText[$replaceText[$replaceText[$get[I];$get[I1];];$get[I2];];$get[I3];];,,;,]]
$var[I0;$split[$get[I];,]]
$var[I4;$arrayAt[I0;$randomNumber[1;12]]]
$var[I;$replaceText[$replaceText[$replaceText[$replaceText[$replaceText[$get[I];$get[I1];];$get[I2];];$get[I3];];$get[I4];];,,;,]]
$var[I0;$split[$get[I];,]]
$var[I5;$arrayAt[I0;$randomNumber[1;11]]]
$var[N0;$split[$get[N];,]]
$var[N1;$arrayAt[N0;$randomNumber[1;15]]]
$var[N;$replaceText[$replaceText[$get[N];$get[N1];];,,;,]]
$var[N0;$split[$get[N];,]]
$var[N2;$arrayAt[N0;$randomNumber[1;14]]]
$var[N;$replaceText[$replaceText[$replaceText[$get[N];$get[N1];];$get[N2];];,,;,]]
$var[N0;$split[$get[N];,]]
$var[N3;$arrayAt[N0;$randomNumber[1;13]]]
$var[N;$replaceText[$replaceText[$replaceText[$replaceText[$get[N];$get[N1];];$get[N2];];$get[N3];];,,;,]]
$var[N0;$split[$get[N];,]]
$var[N4;$arrayAt[N0;$randomNumber[1;12]]]
$var[N;$replaceText[$replaceText[$replaceText[$replaceText[$replaceText[$get[N];$get[N1];];$get[N2];];$get[N3];];$get[N4];];,,;,]]
$var[N0;$split[$get[N];,]]
$var[N5;$arrayAt[N0;$randomNumber[1;11]]]
$var[G0;$split[$get[G];,]]
$var[G1;$arrayAt[G0;$randomNumber[1;15]]]
$var[G;$replaceText[$replaceText[$get[G];$get[G1];];,,;,]]
$var[G0;$split[$get[G];,]]
$var[G2;$arrayAt[G0;$randomNumber[1;14]]]
$var[G;$replaceText[$replaceText[$replaceText[$get[G];$get[G1];];$get[G2];];,,;,]]
$var[G0;$split[$get[G];,]]
$var[G3;$arrayAt[G0;$randomNumber[1;13]]]
$var[G;$replaceText[$replaceText[$replaceText[$replaceText[$get[G];$get[G1];];$get[G2];];$get[G3];];,,;,]]
$var[G0;$split[$get[G];,]]
$var[G4;$arrayAt[G0;$randomNumber[1;12]]]
$var[G;$replaceText[$replaceText[$replaceText[$replaceText[$replaceText[$get[G];$get[G1];];$get[G2];];$get[G3];];$get[G4];];,,;,]]
$var[G0;$split[$get[G];,]]
$var[G5;$arrayAt[G0;$randomNumber[1;11]]]
$var[O0;$split[$get[O];,]]
$var[O1;$arrayAt[O0;$randomNumber[1;15]]]
$var[O;$replaceText[$replaceText[$get[O];$get[O1];];,,;,]]
$var[O0;$split[$get[O];,]]
$var[O2;$arrayAt[O0;$randomNumber[1;14]]]
$var[O;$replaceText[$replaceText[$replaceText[$get[O];$get[O1];];$get[O2];];,,;,]]
$var[O0;$split[$get[O];,]]
$var[O3;$arrayAt[O0;$randomNumber[1;13]]]
$var[O;$replaceText[$replaceText[$replaceText[$replaceText[$get[O];$get[O1];];$get[O2];];$get[O3];];,,;,]]
$var[O0;$split[$get[O];,]]
$var[O4;$arrayAt[O0;$randomNumber[1;12]]]
$var[O;$replaceText[$replaceText[$replaceText[$replaceText[$replaceText[$get[O];$get[O1];];$get[O2];];$get[O3];];$get[O4];];,,;,]]
$var[O0;$split[$get[O];,]]
$var[O5;$arrayAt[O0;$randomNumber[1;11]]]
$setVar[$getQuery[userid]-B1;$get[B1]]

$setVar[$getQuery[userid]-B2;$get[B2]]
$setVar[$getQuery[userid]-B3;$get[B3]]
$setVar[$getQuery[userid]-B4;$get[B4]]
$setVar[$getQuery[userid]-B5;$get[B5]]
$var[Btotal;$get[B1]-$get[B2]-$get[B3]-$get[B4]-$get[B5]]
$setVar[$getQuery[userid]-I1;$get[I1]]

$setVar[$getQuery[userid]-I2;$get[I2]]
$setVar[$getQuery[userid]-I3;$get[I3]]
$setVar[$getQuery[userid]-I4;$get[I4]]
$setVar[$getQuery[userid]-I5;$get[I5]]
$var[Itotal;$get[I1]-$get[I2]-$get[I3]-$get[I4]-$get[I5]]

$setVar[$getQuery[userid]-N1;$get[N1]]

$setVar[$getQuery[userid]-N2;$get[N2]]
$setVar[$getQuery[userid]-N3;free]
$setVar[$getQuery[userid]-N4;$get[N4]]
$setVar[$getQuery[userid]-N5;$get[N5]]
$var[Ntotal;$get[N1]-$get[N2]-$get[N3]-$get[N4]-$get[N5]]

$setVar[$getQuery[userid]-G1;$get[G1]]

$setVar[$getQuery[userid]-G2;$get[G2]]
$setVar[$getQuery[userid]-G3;$get[G3]]
$setVar[$getQuery[userid]-G4;$get[G4]]
$setVar[$getQuery[userid]-G5;$get[G5]]
$var[Gtotal;$get[G1]-$get[G2]-$get[G3]-$get[G4]-$get[G5]]
$setVar[$getQuery[userid]-O1;$get[O1]]

$setVar[$getQuery[userid]-O2;$get[O2]]
$setVar[$getQuery[userid]-O3;$get[O3]]
$setVar[$getQuery[userid]-O4;$get[O4]]
$setVar[$getQuery[userid]-O5;$get[O5]]
$var[Ototal;$get[O1]-$get[O2]-$get[O3]-$get[O4]-$get[O5]]

$setVar[$getQuery[userid]-1B;false]
$setVar[$getQuery[userid]-2B;false]
$setVar[$getQuery[userid]-3B;false]
$setVar[$getQuery[userid]-4B;false]
$setVar[$getQuery[userid]-5B;false]
$setVar[$getQuery[userid]-1I;false]
$setVar[$getQuery[userid]-2I;false]
$setVar[$getQuery[userid]-3I;false]
$setVar[$getQuery[userid]-4I;false]
$setVar[$getQuery[userid]-5I;false]
$setVar[$getQuery[userid]-1N;false]
$setVar[$getQuery[userid]-2N;false]
$setVar[$getQuery[userid]-3N;false]
$setVar[$getQuery[userid]-4N;false]
$setVar[$getQuery[userid]-5N;false]
$setVar[$getQuery[userid]-1G;false]
$setVar[$getQuery[userid]-2G;false]
$setVar[$getQuery[userid]-3G;false]
$setVar[$getQuery[userid]-4G;false]
$setVar[$getQuery[userid]-5G;false]
$setVar[$getQuery[userid]-1O;false]
$setVar[$getQuery[userid]-2O;false]
$setVar[$getQuery[userid]-3O;false]
$setVar[$getQuery[userid]-4O;false]
$setVar[$getQuery[userid]-5O;false]

$if[$getQuery[gameid]==undefined;
$var[gameid;$randomNumber[0000001;999999999]]
$setVar[gameid;$get[gameid]]

$setVar[$get[gameid]-Bplayable;⒈1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,⒑1,11.1,12.1,13.1,14.1,15.1]
  $setVar[$get[gameid]-Iplayable;16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  $setVar[$get[gameid]-Nplayable;31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  $setVar[$get[gameid]-Gplayable;46,47,48,49,50,51,52,53,54,55,56,57,58,59,60]
  $setVar[$get[gameid]-Oplayable;61,62,63,64,65,66,67,68,69,70,71,72,73,74,75]
  $setVar[$get[gameid]-B;0,]
  $setVar[$get[gameid]-I;0,]
  $setVar[$get[gameid]-N;0,]
  $setVar[$get[gameid]-G;0,]
  $setVar[$get[gameid]-O;0,]
  $setVar[$get[gameid]-Bcount;15]
  $setVar[$get[gameid]-Icount;15]
  $setVar[$get[gameid]-Ncount;15]
  $setVar[$get[gameid]-Gcount;15]
  $setVar[$get[gameid]-Ocount;15];]
$send[200;json;{
"image": "https://shadows-api-v2.shadowsnemesis.repl.co/game/bingo/bingocardimage?userid=$getQuery[userid]",
"B": "$get[Btotal]",
"I": "$get[Itotal]",
"N": "$get[Ntotal]",
"G": "$get[Gtotal]",
"O": "$get[Ototal]",
"gameid": "$get[gameid]"
}]
`
}